import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "./components/home/MenuBar";
import Footer from "./components/home/Footer";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <MenuBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
