import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "../components/home/MenuBar";
import Footer from "../components/home/Footer";
import { ReactNode } from "react";
import CartProvider from "@/context/product/CartContext";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>): ReactNode {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <MenuBar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
